server:
  port: 8082
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: test
    username: guest
    password: guest
rocketmq:
  name-server: 127.0.0.1:9876
  #生产者配置
  producer:
    group: cc-producer-group
    #目的地（topic:tag）
    #topic
    topic: cc-topic
    #sync tag(同步消息tag)
    sync-tag: cc-sync-tags
    #async tag(异步消息tag)
    async-tag: cc-async-tags
    #oneway tag(单向消息tag)
    oneway-tag: cc-oneway-tags
