server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zx_db?&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  redis:
    port: 6379
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10
        max-wait: 10000
mybatis:
  mapper-locations: classpath*:com/just/cc/dao/mapper/*.xml