server:
  port: 8083
spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: test
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: manual
rocketmq:
  name-server: 127.0.0.1:9876